export interface Topic {
  id:     string;
  korean: string;
  english: string;
  icon:   string;
  chips:  string[];
}

export interface Word {
  id:         string;
  korean:     string;
  english:    string;
  difficulty: 'lower_beginner' | 'upper_beginner' | 'intermediate';
  example?:   string;
}

// Grammar pattern generated by LLM (no fixed DB)
export interface GrammarPattern {
  id:      string;   // e.g. "g1", "g2"
  pattern: string;   // e.g. "-(으)니까"
  meaning: string;   // e.g. "because / since"
  example: string;   // Korean example sentence
}

// One section in the speech timeline
export interface TimelineSection {
  id:    string;
  label: string;           // e.g. "Open", "The story"
  cue:   string;           // Speaking prompt in English
  words: {
    id:      string;
    korean:  string;
    english: string;
  }[];
  grammar: GrammarPattern | null;  // Grammar attached to this section (or null)
}

// Legacy — kept for backward compatibility if needed
export interface Grammar {
  id:      string;
  korean:  string;
  english: string;
  example: string;
}